<a href="https://colab.research.google.com/github/eric-castillo05/emotions-wheel-nlp/blob/main/ELMo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [67]:
%pip install -U datasets

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 491.5/491.5 kB 10.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 193.6/193.6 kB 12.4 MB/s eta 0:00:00
  Attempting uninstall: fsspec
    Found existing installation: fsspec 2025.3.2
    Uninstalling fsspec-2025.3.2:
      Successfully uninstalled fsspec-2025.3.2
  Attempting uninstall: datasets
    Found existing installation: datasets 2.14.4
    Uninstalling datasets-2.14.4:
      Successfully uninstalled datasets-2.14.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
gcsfs 2025.3.2 requires fsspec==2025.3.2, but you have fsspec 2025.3.0 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cublas-cu12==12.4.5.8; platform_system == "Linux" and platform_machine == "x86_64", but you have nvidia-cublas-cu12 12.5.3.2 which is incompatible.
torch 2.6.0+cu124 requires nvidia-cuda-cupti-cu12==12.4.127; pl

In [50]:
import polars as pl
from datasets import load_dataset
import pickle
import numpy as np

In [8]:
ds = load_dataset("Jsevisal/go_emotions_wheel")

/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


In [9]:
df = pl.from_dicts(ds['train'][:])

In [10]:
df.head()

shape: (5, 3)
┌─────────────────────────────────┬───────────┬─────────┐
│ text                            ┆ labels    ┆ id      │
│ ---                             ┆ ---       ┆ ---     │
│ str                             ┆ list[i64] ┆ str     │
╞═════════════════════════════════╪═══════════╪═════════╡
│ My favourite food is anything … ┆ [5]       ┆ eebbqej │
│ Now if he does off himself, ev… ┆ [5]       ┆ ed00q6i │
│ WHY THE FUCK IS BAYLESS ISOING  ┆ [7]       ┆ eezlygj │
│ To make her feel threatened     ┆ [2]       ┆ ed7ypvh │
│ Dirty Southern Wankers          ┆ [7]       ┆ ed0bdzj │
└─────────────────────────────────┴───────────┴─────────┘

In [ ]:
df.sample(10)

shape: (10, 3)
┌─────────────────────────────────┬───────────┬─────────┐
│ text                            ┆ labels    ┆ id      │
│ ---                             ┆ ---       ┆ ---     │
│ str                             ┆ list[i64] ┆ str     │
╞═════════════════════════════════╪═══════════╪═════════╡
│ Chasing thoughts and storing t… ┆ [1]       ┆ ed6eaf9 │
│ That boy ain’t right            ┆ [7]       ┆ ed7f2g9 │
│ That's what we're doing. It's … ┆ [5]       ┆ edw3uza │
│ Well to be fair to these idiot… ┆ [7]       ┆ eei3vrb │
│ They're not going to read thei… ┆ [7]       ┆ eegdb9r │
│ Well it looks like I am going … ┆ [3]       ┆ edu13rb │
│ Looks like modern art tbh but … ┆ [0]       ┆ eduk4z3 │
│ They will just throw themselve… ┆ [5]       ┆ ef4hcdo │
│ Sour Tangie!                    ┆ [5]       ┆ edhwi8w │
│ Yeah they are! I didn't realiz… ┆ [0]       ┆ eev76f6 │
└─────────────────────────────────┴───────────┴─────────┘

In [5]:
%pip install spacy

In [6]:
%pip install spacy_cleaner

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.6/57.6 kB 3.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 26.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.5/98.5 MB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 kB 6.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 920.2/920.2 kB 48.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 83.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.2/10.2 MB 109.9 MB/s eta 0:00:00
  Attempting uninstall: tqdm
    Found existing installation: tqdm 4.67.1
    Uninstalling tqdm-4.67.1:
      Successfully uninstalled tqdm-4.67.1
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: blis
    Found existing installation: blis 1.3.0

In [1]:
import spacy
import spacy_cleaner
from spacy_cleaner.processing import removers, replacers, mutators

In [12]:
!python3 -m spacy download en_core_web_lg

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 587.7/587.7 MB 2.2 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_lg')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.


In [2]:
nlp = spacy.load("en_core_web_lg")

In [11]:
docs = df.select('text').to_series().to_list()

In [12]:
docs[:10]

["My favourite food is anything I didn't have to cook myself.",
 'Now if he does off himself, everyone will think hes having a laugh screwing with people instead of actually dead',
 'WHY THE FUCK IS BAYLESS ISOING',
 'To make her feel threatened',
 'Dirty Southern Wankers',
 "OmG pEyToN iSn'T gOoD eNoUgH tO hElP uS iN tHe PlAyOfFs! Dumbass Broncos fans circa December 2015.",
 'Yes I heard abt the f bombs! That has to be why. Thanks for your reply:) until then hubby and I will anxiously wait 😝',
 'We need more boards and to create a bit more space for [NAME]. Then we’ll be good.',
 'Damn youtube and outrage drama is super lucrative for reddit',
 'It might be linked to the trust factor of your friend.']

In [13]:
from spacy_cleaner import processing, Cleaner

pipeline = spacy_cleaner.Cleaner(
    nlp,
    processing.remove_number_token,
    processing.remove_punctuation_token,
    processing.mutate_lemma_token,
)

In [14]:
def clean(text, nlp):
    doc = nlp(text.lower())
    tokens = []
    for token in doc:
        if not token.is_digit and not token.is_punct and not token.is_space:
            tokens.append(token.lemma_)
    return ' '.join(tokens)

In [ ]:
docs = df.select('text').to_series().to_list()
r = [clean(doc, nlp) for doc in docs]

In [ ]:
df = df.with_columns(
    pl.Series('clean-text', r).alias('clean-text')
)

In [ ]:
df.head()

shape: (5, 4)
┌─────────────────────────────────┬───────────┬─────────┬─────────────────────────────────┐
│ text                            ┆ labels    ┆ id      ┆ clean-text                      │
│ ---                             ┆ ---       ┆ ---     ┆ ---                             │
│ str                             ┆ list[i64] ┆ str     ┆ str                             │
╞═════════════════════════════════╪═══════════╪═════════╪═════════════════════════════════╡
│ My favourite food is anything … ┆ [5]       ┆ eebbqej ┆ my favourite food be anything … │
│ Now if he does off himself, ev… ┆ [5]       ┆ ed00q6i ┆ now if he do off himself every… │
│ WHY THE FUCK IS BAYLESS ISOING  ┆ [7]       ┆ eezlygj ┆ why the fuck be bayless isoing  │
│ To make her feel threatened     ┆ [2]       ┆ ed7ypvh ┆ to make she feel threaten       │
│ Dirty Southern Wankers          ┆ [7]       ┆ ed0bdzj ┆ dirty southern wanker           │
└─────────────────────────────────┴───────────┴─────────┴─────────────────────────────────┘

In [ ]:
with open('train-clean.pkl', 'wb') as f:
  pickle.dump(df, f)

In [ ]:
with open('train-clean.pkl', 'rb') as f:
  df_loaded = pickle.load(f)

In [15]:
df_test = pl.from_dicts(ds['test'][:])

In [16]:
docs = df_test.select('text').to_series().to_list()

In [17]:
docs[:10]

['I’m really sorry about your situation :( Although I love the names Sapphira, Cirilla, and Scarlett!',
 "It's wonderful because it's awful. At not with.",
 'Kings fan here, good luck to you guys! Will be an interesting game to watch! ',
 "I didn't know that, thank you for teaching me something today!",
 'They got bored from haunting earth for thousands of years and ultimately moved on to the afterlife.',
 'Thank you for asking questions and recognizing that there may be things that you don’t know or understand about police tactics. Seriously. Thank you.',
 'You’re welcome',
 '100%! Congrats on your job too!',
 'I’m sorry to hear that friend :(. It’s for the best most likely if she didn’t accept you for who you are',
 'Girlfriend weak as well, that jump was pathetic.']

In [18]:
r = [clean(doc, nlp) for doc in docs]

In [20]:
df_test = df_test.with_columns(
    pl.Series('clean-text', r).alias('clean-text')
)

In [21]:
df_test.head()

shape: (5, 4)
┌─────────────────────────────────┬───────────┬─────────┬─────────────────────────────────┐
│ text                            ┆ labels    ┆ id      ┆ clean-text                      │
│ ---                             ┆ ---       ┆ ---     ┆ ---                             │
│ str                             ┆ list[i64] ┆ str     ┆ str                             │
╞═════════════════════════════════╪═══════════╪═════════╪═════════════════════════════════╡
│ I’m really sorry about your si… ┆ [4]       ┆ eecwqtt ┆ I ’m really sorry about your s… │
│ It's wonderful because it's aw… ┆ [0]       ┆ ed5f85d ┆ it be wonderful because it be … │
│ Kings fan here, good luck to y… ┆ [0]       ┆ een27c3 ┆ kings fan here good luck to yo… │
│ I didn't know that, thank you … ┆ [0]       ┆ eelgwd1 ┆ I do not know that thank you f… │
│ They got bored from haunting e… ┆ [5]       ┆ eem5uti ┆ they get bored from haunt eart… │
└─────────────────────────────────┴───────────┴─────────┴─────────────────────────────────┘

In [22]:
with open('test-clean.pkl', 'wb') as f:
  pickle.dump(df_test, f)

In [43]:
with open('train-clean.pkl', 'rb') as f:
  df_train = pickle.load(f)

In [28]:
import tensorflow_hub as hub
import tensorflow as tf

In [29]:
model = "https://tfhub.dev/google/elmo/3"
elmo = hub.load(model).signatures['default']

In [7]:
x = ["Roasted ants are a popular snack in Columbia"]

In [10]:
embeddings = elmo(tf.constant(x))["elmo"]

In [13]:
embeddings.shape

TensorShape([1, 8, 1024])

In [30]:
def elmo_vectors(x):
  embeddings = elmo(tf.constant(list(x)))["elmo"]
  return tf.reduce_mean(embeddings, axis = 1)

In [33]:
elmo_vectors(x)

<tf.Tensor: shape=(1, 1024), dtype=float32, numpy=
array([[-0.08238705,  0.07898237,  0.08993176, ..., -0.22516635,
         0.0555426 ,  0.29672703]], dtype=float32)>

In [34]:
list_train = [df_train[i:i+100] for i in range(0, df_train.shape[0], 100)]

In [37]:
list_train

[shape: (100, 4)
 ┌─────────────────────────────────┬───────────┬─────────┬─────────────────────────────────┐
 │ text                            ┆ labels    ┆ id      ┆ clean-text                      │
 │ ---                             ┆ ---       ┆ ---     ┆ ---                             │
 │ str                             ┆ list[i64] ┆ str     ┆ str                             │
 ╞═════════════════════════════════╪═══════════╪═════════╪═════════════════════════════════╡
 │ My favourite food is anything … ┆ [5]       ┆ eebbqej ┆ my favourite food be anything … │
 │ Now if he does off himself, ev… ┆ [5]       ┆ ed00q6i ┆ now if he do off himself every… │
 │ WHY THE FUCK IS BAYLESS ISOING  ┆ [7]       ┆ eezlygj ┆ why the fuck be bayless isoing  │
 │ To make her feel threatened     ┆ [2]       ┆ ed7ypvh ┆ to make she feel threaten       │
 │ Dirty Southern Wankers          ┆ [7]       ┆ ed0bdzj ┆ dirty southern wanker           │
 │ …                               ┆ …         ┆ …   

In [38]:
elmo_train = [elmo_vectors(x['clean-text']) for x in list_train]

In [39]:
with open ('elmo-train.pkl', 'wb') as f:
  pickle.dump(elmo_train, f)

In [34]:
with open ('elmo-train.pkl', 'rb') as f:
  elmo_train = pickle.load(f)

In [23]:
with open ('test-clean.pkl', 'rb') as f:
  df_test = pickle.load(f)

In [24]:
df_test.head()

shape: (5, 4)
┌─────────────────────────────────┬───────────┬─────────┬─────────────────────────────────┐
│ text                            ┆ labels    ┆ id      ┆ clean-text                      │
│ ---                             ┆ ---       ┆ ---     ┆ ---                             │
│ str                             ┆ list[i64] ┆ str     ┆ str                             │
╞═════════════════════════════════╪═══════════╪═════════╪═════════════════════════════════╡
│ I’m really sorry about your si… ┆ [4]       ┆ eecwqtt ┆ I ’m really sorry about your s… │
│ It's wonderful because it's aw… ┆ [0]       ┆ ed5f85d ┆ it be wonderful because it be … │
│ Kings fan here, good luck to y… ┆ [0]       ┆ een27c3 ┆ kings fan here good luck to yo… │
│ I didn't know that, thank you … ┆ [0]       ┆ eelgwd1 ┆ I do not know that thank you f… │
│ They got bored from haunting e… ┆ [5]       ┆ eem5uti ┆ they get bored from haunt eart… │
└─────────────────────────────────┴───────────┴─────────┴─────────────────────────────────┘

In [25]:
list_test = [df_test[i:i+100] for i in range(0, df_test.shape[0], 100)]

In [31]:
elmo_test = [elmo_vectors(x['clean-text']) for x in list_test]

In [35]:
elmo_train[0]

<tf.Tensor: shape=(100, 1024), dtype=float32, numpy=
array([[-2.0681649e-02, -8.5263856e-02,  1.7512901e-01, ...,
         7.0279561e-02,  9.6149398e-03, -3.8381062e-02],
       [ 3.1486779e-02, -2.1465714e-01,  6.5056026e-02, ...,
        -1.0497018e-01,  2.5125861e-01, -4.5484155e-03],
       [-4.1211601e-02, -7.7113435e-02,  6.7862630e-02, ...,
         1.7554160e-02,  4.5680344e-02, -2.0435799e-04],
       ...,
       [-4.0909234e-03, -2.9983314e-02,  4.9977276e-02, ...,
         1.0161781e-03,  4.1756029e-03,  3.1077968e-02],
       [-1.3440171e-01, -7.2128318e-02,  7.0494756e-02, ...,
        -1.4836657e-01,  2.4608071e-01,  8.2392097e-02],
       [-1.5808007e-02, -4.1046936e-02,  9.1421835e-02, ...,
         2.3020994e-02,  8.2198702e-02,  8.5115461e-03]], dtype=float32)>

In [32]:
elmo_test[0]

<tf.Tensor: shape=(100, 1024), dtype=float32, numpy=
array([[-0.17682931, -0.22035474,  0.01862513, ..., -0.04123634,
         0.2526633 ,  0.09986784],
       [-0.00667305, -0.12619969,  0.08694158, ...,  0.06372865,
         0.09755841,  0.00682761],
       [ 0.11470237, -0.11503435,  0.08863897, ..., -0.08438297,
         0.14478947,  0.0965043 ],
       ...,
       [-0.03638997, -0.03044155,  0.00893117, ...,  0.0151472 ,
         0.05176874,  0.02279315],
       [-0.09297485, -0.02054822,  0.05247753, ..., -0.01451083,
        -0.00449983,  0.01621042],
       [-0.15631011, -0.36106104,  0.09781794, ..., -0.1413809 ,
         0.31204474,  0.05306143]], dtype=float32)>

In [37]:
with open ('elmo-test.pkl', 'wb') as f:
  pickle.dump(elmo_test, f)

In [38]:
from sklearn.model_selection import train_test_split

In [51]:
elmo_train = np.concatenate(elmo_train, axis = 0)

In [53]:
elmo_test = np.concatenate(elmo_test, axis = 0)

In [45]:
df_train.columns

['text', 'labels', 'id', 'clean-text']

In [96]:
labels = df['labels'].list.first().to_numpy()

In [97]:
xtrain, xtest, ytrain, ytest = train_test_split(elmo_train, labels, random_state= 42, test_size = 0.3)

In [98]:
ytrain

array([5, 5, 2, ..., 0, 5, 5])

In [99]:
xtrain

array([[ 0.00607651,  0.0582052 ,  0.0723213 , ...,  0.00033965,
         0.08250277,  0.02522242],
       [ 0.00471205, -0.05953115,  0.12593208, ...,  0.01524406,
        -0.00205653, -0.01741741],
       [-0.21342932, -0.04873699,  0.07200867, ...,  0.0286433 ,
         0.0026263 ,  0.02424349],
       ...,
       [-0.07265137, -0.14496584,  0.07978438, ..., -0.00850828,
         0.16661869,  0.00560322],
       [-0.27011105, -0.23452963, -0.10076138, ...,  0.21002963,
         0.05528736, -0.08217276],
       [ 0.04445035,  0.05976005,  0.05709243, ..., -0.03417368,
         0.2831142 ,  0.06816049]], dtype=float32)

In [100]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score

In [141]:
lreg = LogisticRegression(class_weight='balanced', multi_class='auto', max_iter = 1000)

In [142]:
lreg.fit(xtrain, ytrain)

LogisticRegression(class_weight='balanced', max_iter=1000, multi_class='auto')

In [143]:
y_pred = lreg.predict(xtest)

In [144]:
from sklearn.metrics import f1_score, classification_report

print(classification_report(ytest, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.61      0.68      3873
           1       0.29      0.41      0.34      1087
           2       0.19      0.53      0.28       196
           3       0.43      0.51      0.47      1373
           4       0.33      0.47      0.39       776
           5       0.61      0.41      0.49      3814
           6       0.20      0.58      0.30       163
           7       0.40      0.40      0.40      1573
           8       0.10      0.39      0.16       168

    accuracy                           0.48     13023
   macro avg       0.37      0.48      0.39     13023
weighted avg       0.56      0.48      0.51     13023

